name: flutter_native_image_platform_interface
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.7
# homepage: https://konseben.dev
# issue_tracker: https://github.com/btastic/flutter_native_image/issues
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
